{%- macro envioller_conf(envioller_config) %}
    {%- for key, value in envioller_config.items() %}

[{{ key }}]
        {%- if value is mapping %}
            {%- for key2, value2 in value.items() %}
                        {%- if value2 is number %}
{{ key2 }}: {{ value2 }}
                        {%- elif value2 is string %}
{{ key2 }}: {{ value2 }}
                        {%- elif value2 is undefined or value2 is none%}
{{ key2 }}:
                        {%- endif -%}
            {%- endfor -%}
        {%- endif -%}
    {%- endfor -%}
{%- endmacro -%}
# ENVIOLLER configuration file.
#
# **** DO NOT EDIT THIS FILE ****
#
# This file is managed by Salt via {{ source }}
{{ envioller_conf(config) }}
