FROM ubuntu:focal
MAINTAINER envio.systems

ARG MINION_ID
ENV APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update -y
RUN apt-get install apt-utils wget gnupg -y

RUN wget -q https://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest/SALTSTACK-GPG-KEY.pub && \
    apt-key add SALTSTACK-GPG-KEY.pub && \
    rm SALTSTACK-GPG-KEY.pub

RUN echo "deb http://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest focal main" > /etc/apt/sources.list.d/saltstack.list

RUN apt-get update -y && \
    apt-get install salt-minion salt-ssh -y && \
    apt-get clean all
    
RUN echo "id: ${MINION_ID}" > /etc/salt/minion.d/id.conf

ENTRYPOINT ["salt-minion", "-l", "debug"]